[package]
name = "tamrl"
version = "0.1.0"
authors = ["@jlandic"]
edition = "2018"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
gdnative = "0.9.3"
bevy_ecs = "0.6.0"
itertools = "0.10.3"
pathfinding = "3.0.8"