name: CI

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0
  RUST_BACKTRACE: 1

  GDRUST_FEATURES: "gdnative/async,gdnative/serde"

on:
  pull_request:
    branches:
      - master

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Install Rust"
        uses: ./.github/composite/rust
        with:
          components: rustfmt
      - name: "Check rustfmt"
        run: cargo fmt --all -- --check;

  clippy:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.rust == 'nightly' }}
    steps:
      - uses: actions/checkout@v2
      - name: "Install Rust"
        uses: ./.github/composite/rust
        with:
          components: clippy
      - name: "Check clippy"
        run: cargo clippy --workspace --features ${GDRUST_FEATURES} -- -D clippy::style -D clippy::complexity -D clippy::perf -D clippy::dbg_macro -D clippy::todo -D clippy::unimplemented;

  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Install Rust"
        uses: ./.github/composite/rust
      - name: "Compile tests"
        run: cargo test --workspace --features ${GDRUST_FEATURES} --no-run;
      - name: "Test"
        run: cargo test --workspace --features ${GDRUST_FEATURES};
